#!/usr/bin/env bash
export KAFKA_ID=kafkaperftest
export MOCKSERVER_ID=mockserver
export DB_ID=mysql
export SLEEP_FACTOR_IN_SECONDS=5
export DBUSER=central_ledger
export DBPASS=password
export DBNAME=central_ledger
export DB_SLEEPTIME=15
export MESSAGES_BATCH_SIZE=1000
export FSP1="dfsp1"
export FSP2="dfsp2"
export SCRIPT_DIR=scripts
