ignore:
  # Ignore cross-spawn vulnerabilities by CVE ID due to false positive
  # as grype looks at package-lock.json where it shows versions with
  # vulnerabilities, npm ls shows only 7.0.6 verion is used

  # Ignore OpenSSL vulnerabilities in Alpine libcrypto3 and libssl3
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9232
  - vulnerability: CVE-2025-9231
  - vulnerability: GHSA-5j98-mcp5-4vw2 # glob, which comes from npm
  - vulnerability: CVE-2025-60876
  - vulnerability: CVE-2026-22184
  - vulnerability: GHSA-34x7-hfp2-rc4v
  - vulnerability: CVE-2025-69420
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-8qq5-rm4j-mr97
  - vulnerability: GHSA-xxjr-mmjv-4gpg
  - vulnerability: CVE-2026-22796
  - vulnerability: GHSA-g9mf-h72j-4rw9
  # Ignore fast-xml-parser 4.5.3 vulnerability
  - vulnerability: GHSA-37qj-frw5-hhjh
    package: fast-xml-parser
    version: 4.5.3
  # Ignore eslint 8.57.1 medium severity vulnerability
  - vulnerability: GHSA-p5wg-g6qr-c7cg
    package: eslint
    version: 8.57.1
# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
