ignore:
  # Ignore cross-spawn vulnerabilities by CVE ID due to false positive
  # as grype looks at package-lock.json where it shows versions with
  # vulnerabilities, npm ls shows only 7.0.6 verion is used

  # Ignore OpenSSL vulnerabilities in Alpine libcrypto3 and libssl3
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9232
  - vulnerability: CVE-2025-9231
  - vulnerability: GHSA-5j98-mcp5-4vw2 # glob, which comes from npm
  - vulnerability: CVE-2025-60876
  - vulnerability: CVE-2026-22184
  # Node.js vulnerabilities - fix requires Node 22.22.0+ (not yet available in Alpine)
  - vulnerability: CVE-2025-59465
  - vulnerability: CVE-2025-55131
  - vulnerability: CVE-2026-21637
  - vulnerability: CVE-2025-59466
  - vulnerability: CVE-2025-55130
  - vulnerability: CVE-2025-55132
  # diff npm package - fix requires 5.2.2 (breaking change)
  - vulnerability: GHSA-73rr-hh4g-fpgx
  # tar npm package - fix requires 7.5.3+ (major version upgrade)
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-8qq5-rm4j-mr97
  # OpenSSL vulnerabilities - fix requires Alpine package update
  - vulnerability: CVE-2026-22796

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
