ignore:
  # Ignore cross-spawn vulnerabilities by CVE ID due to false positive
  # as grype looks at package-lock.json where it shows versions with
  # vulnerabilities, npm ls shows only 7.0.6 verion is used

  # Ignore OpenSSL vulnerabilities in Alpine libcrypto3 and libssl3
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9232
  - vulnerability: CVE-2025-9231
  - vulnerability: GHSA-5j98-mcp5-4vw2 # glob, which comes from npm
  - vulnerability: CVE-2025-60876

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
