instrumentation:
  include-all-sources: true
  excludes: ['**/migrations/**', '**/deploy/**', '**/src/domain/settlements/settlementEventListener.js', '**/testPI2/**']
check:
  global:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
  each:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
