apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: central-ledger
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/'
  labels:
      app: central-ledger
spec:
  rules:
    - host: central-ledger.local
      http:
        paths:
        - path: /
          backend:
            serviceName: central-ledger
            servicePort: 3000
        - path: /admin
          backend:
            serviceName: central-ledger
            servicePort: 3001