jobs:
  # Runs extended coverage checks againts unit integration and fuzz tests.
  # I've added this here for now since we need to go upstream to the circleci orb and 
  # update coverage to run on a machine since the integration and fuzz tests require a machine
  # executor, not Docker.
  coverage-check-all:
    executor:
      name: build/machine
    steps:
      - build/machine_dependencies
      - checkout
      - build/configure_nvm
      - build/display_versions
      - attach_workspace:
          at: /tmp
      - run:
          name: Create dir for test results
          command: mkdir -p ./test/results
      - run:
          name: Install dependencies
          command: |
            nvm use default
            npm ci
      - run:
          name: Execute coverage check
          command: |
            # Set Node version to default (Note: this is needed on Ubuntu)
            nvm use default
            ./node_modules/.bin/ts-node src/testing/run.ts coverage --type=all
      - store_artifacts:
          path: coverage
          destination: test
      - store_test_results:
          path: coverage

  # Runs the fuzz tests.
  fuzz:
    executor:
      name: build/machine
    steps:
      - build/machine_dependencies
      - checkout
      - build/configure_nvm
      - build/display_versions
      - attach_workspace:
          at: /tmp
      - run:
          name: Create dir for test results
          command: mkdir -p ./test/results
      - run:
          name: Install dependencies
          command: |
            nvm use default
            npm ci
      - run:
          name: Execute fuzz tests
          command: |
            # Set Node version to default (Note: this is needed on Ubuntu)
            nvm use default
            npm run test:fuzz
          environment:
            LOG_LEVEL: warn
      - store_artifacts:
          path: .fuzz_output
          destination: test

workflows:
  build_and_test:
    jobs:
      - coverage-check-all:
          name: coverage-check-all
          context: org-global
          filters:
            tags:
              only: /v\d+(\.\d+){2}/
      - fuzz:
          name: fuzz
          context: org-global
          filters:
            tags:
              only: /v\d+(\.\d+){2}/