version: 2.1
orbs:
  build: mojaloop/build@1.0.58
  slack: circleci/slack@4.12.5

executors:
  default-docker:
    working_directory: &WORKING_DIR /home/circleci/project
    shell: "/bin/sh -leo pipefail" ## Ref: https://circleci.com/docs/env-vars/#alpine-linux
    environment:
      BASH_ENV: /etc/profile ## Ref: https://circleci.com/docs/env-vars/#alpine-linux
      NVM_ARCH_UNOFFICIAL_OVERRIDE: x64-musl ## Ref: https://github.com/nvm-sh/nvm/issues/1102#issuecomment-550572252
    docker:
      - image: node:18-alpine3.19 # Ref: https://hub.docker.com/_/node?tab=tags&page=1&name=alpine

defaults_configure_git: &defaults_configure_git
  name: Configure git
  command: |
    git config user.email ${GIT_CI_EMAIL}
    git config user.name ${GIT_CI_USER}

defaults_environment: &defaults_environment
  ## env var for nx to set main branch
  MAIN_BRANCH_NAME: main
  ## Disable LIBRDKAFKA build since we install it via general dependencies
  # BUILD_LIBRDKAFKA: 0

defaults_docker_Dependencies: &defaults_docker_Dependencies |
  apk --no-cache add bash
  apk --no-cache add git
  apk --no-cache add ca-certificates
  apk --no-cache add curl
  apk --no-cache add openssh-client
  apk --no-cache add -t build-dependencies make gcc g++ python3 libtool autoconf automake jq
  apk --no-cache add -t openssl ncurses coreutils libgcc linux-headers grep util-linux binutils findutils
  apk --no-cache add librdkafka-dev

jobs:
  release:
    executor: default-docker
    environment:
      <<: *defaults_environment
    steps:
      - run:
          name: Install general dependencies
          command: *defaults_docker_Dependencies
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          <<: *defaults_configure_git
      - run:
          name: Setup Slack config
          command: |
            echo "export SLACK_PROJECT_NAME=${CIRCLE_PROJECT_REPONAME}" >> $BASH_ENV
            echo "export SLACK_RELEASE_TYPE='GitHub Release'" >> $BASH_ENV
            echo "export SLACK_RELEASE_TAG='${RELEASE_TAG} on ${CIRCLE_BRANCH} branch'" >> $BASH_ENV
            echo "export SLACK_BUILD_ID=${CIRCLE_BUILD_NUM}" >> $BASH_ENV
            echo "export SLACK_CI_URL=${CIRCLE_BUILD_URL}" >> $BASH_ENV
      - run:
          name: Generate changelog and bump package version
          command: npm run release -- --no-verify
      - run:
          name: Generate SBOM
          command: bash .circleci/sbom.sh
      - run:
          name: Push the release
          command: git push --follow-tags origin ${CIRCLE_BRANCH}
      - slack/notify:
          event: fail
          template: SLACK_TEMP_RELEASE_FAILURE
workflows:
  build_and_test:
    jobs:
      - build/workflow:
          context: org-global
          filters:
            tags:
              only: /v\d+(\.\d+){2}(-[a-zA-Z-][0-9a-zA-Z-]*\.\d+)?/
      - pr-tools/pr-title-check:
          context: org-global
      - setup:
          context: org-global
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - test-lint:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - test-unit:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - test-coverage:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - test-integration:
          context: org-global
          requires:
            - setup
            - build-local
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - test-functional:
          context: org-global
          requires:
            - setup
            - build-local
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - vulnerability-check:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - audit-licenses:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - license-scan:
          context: org-global
          requires:
            - build-local
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(\-snapshot(\.[0-9]+)?)?(\-hotfix(\.[0-9]+)?)?(\-perf(\.[0-9]+)?)?/
            branches:
              ignore:
                - /.*/
      - image-scan:
          context: org-global
          requires:
            - build-local
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(\-snapshot(\.[0-9]+)?)?(\-hotfix(\.[0-9]+)?)?(\-perf(\.[0-9]+)?)?/
            branches:
              ignore:
                - /.*/
      - release:
          context: org-global
          requires:
            - pr-tools/pr-title-check
            ## Only do this check on PRs
            # - test-dependencies
            - test-lint
            - test-unit
            - test-coverage
            - test-integration
            - test-functional
            - vulnerability-check
            - audit-licenses
            - license-scan
            - image-scan
          filters:
            branches:
              only:
                - main
                - /release\/v.*/
