/*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Georgi Georgiev <georgi.georgiev@modusbox.com>
 --------------
 ******/

'use strict'

const balanceOfPayments = [
  { 'balanceOfPaymentsId': 993, 'name': '993', 'description': '1. Current account' },
  { 'balanceOfPaymentsId': 100, 'name': '100', 'description': 'A. Goods' },
  { 'balanceOfPaymentsId': 110, 'name': '110', 'description': '1. General merchandise' },
  { 'balanceOfPaymentsId': 11010, 'name': '110 B', 'description': '1.1 Export/import of goods in trade statistics' },
  { 'balanceOfPaymentsId': 11020, 'name': '110 C', 'description': '1.2 Adjustments to trade statistics' },
  { 'balanceOfPaymentsId': 11030, 'name': '110 CA', 'description': '1.3 For coverage' },
  { 'balanceOfPaymentsId': 11040, 'name': '110 CB', 'description': '1.4 For classification' },
  { 'balanceOfPaymentsId': 11050, 'name': '110 CC', 'description': '1.5 For valuation' },
  { 'balanceOfPaymentsId': 11060, 'name': '110 CD', 'description': '1.6 For timing' },
  { 'balanceOfPaymentsId': 150, 'name': '150', 'description': '2. Goods for processing' },
  { 'balanceOfPaymentsId': 151, 'name': '151', 'description': '2.1 Processing abroad' },
  { 'balanceOfPaymentsId': 152, 'name': '152', 'description': '2.2 Processing in the compiling economy' },
  { 'balanceOfPaymentsId': 160, 'name': '160', 'description': '3. Repairs on goods' },
  { 'balanceOfPaymentsId': 170, 'name': '170', 'description': '4. Goods procured in ports by carriers' },
  { 'balanceOfPaymentsId': 171, 'name': '171', 'description': '4.1 In seaports' },
  { 'balanceOfPaymentsId': 172, 'name': '172', 'description': '4.2 In airports' },
  { 'balanceOfPaymentsId': 173, 'name': '173', 'description': '4.3 In other ports' },
  { 'balanceOfPaymentsId': 180, 'name': '180', 'description': '5. Nonmonetary gold' },
  { 'balanceOfPaymentsId': 181, 'name': '181', 'description': '5.1 Held as a store of value' },
  { 'balanceOfPaymentsId': 182, 'name': '182', 'description': '5.2 Other' },
  { 'balanceOfPaymentsId': 200, 'name': '200', 'description': 'B. Services' },
  { 'balanceOfPaymentsId': 205, 'name': '205', 'description': '1. Transportation' },
  { 'balanceOfPaymentsId': 850, 'name': '850', 'description': 'Total passenger' },
  { 'balanceOfPaymentsId': 851, 'name': '851', 'description': 'Total freight' },
  { 'balanceOfPaymentsId': 852, 'name': '852', 'description': 'Total other services' },
  { 'balanceOfPaymentsId': 206, 'name': '206', 'description': '1.1 Sea transport' },
  { 'balanceOfPaymentsId': 207, 'name': '207', 'description': '1.1.1 Passenger' },
  { 'balanceOfPaymentsId': 208, 'name': '208', 'description': '1.1.2 Freight' },
  { 'balanceOfPaymentsId': 209, 'name': '209', 'description': '1.1.3 Other' },
  { 'balanceOfPaymentsId': 210, 'name': '210', 'description': '1.2 Air transport' },
  { 'balanceOfPaymentsId': 211, 'name': '211', 'description': '1.2.1 Passenger' },
  { 'balanceOfPaymentsId': 212, 'name': '212', 'description': '1.2.2 Freight' },
  { 'balanceOfPaymentsId': 213, 'name': '213', 'description': '1.2.3 Other' },
  { 'balanceOfPaymentsId': 214, 'name': '214', 'description': '1.3 Other transport' },
  { 'balanceOfPaymentsId': 215, 'name': '215', 'description': '1.3.1 Passenger' },
  { 'balanceOfPaymentsId': 216, 'name': '216', 'description': '1.3.2 Freight' },
  { 'balanceOfPaymentsId': 217, 'name': '217', 'description': '1.3.3 Other' },
  { 'balanceOfPaymentsId': 218, 'name': '218', 'description': '1.4 Space transport' },
  { 'balanceOfPaymentsId': 219, 'name': '219', 'description': '1.5 Rail transport' },
  { 'balanceOfPaymentsId': 220, 'name': '220', 'description': '1.5.1 Passenger' },
  { 'balanceOfPaymentsId': 221, 'name': '221', 'description': '1.5.2 Freight' },
  { 'balanceOfPaymentsId': 222, 'name': '222', 'description': '1.5.3 Other' },
  { 'balanceOfPaymentsId': 223, 'name': '223', 'description': '1.6 Road transport' },
  { 'balanceOfPaymentsId': 224, 'name': '224', 'description': '1.6.1 Passenger' },
  { 'balanceOfPaymentsId': 225, 'name': '225', 'description': '1.6.2 Freight' },
  { 'balanceOfPaymentsId': 226, 'name': '226', 'description': '1.6.3 Other' },
  { 'balanceOfPaymentsId': 227, 'name': '227', 'description': '1.7 Inland waterway transport' },
  { 'balanceOfPaymentsId': 228, 'name': '228', 'description': '1.7.1 Passenger' },
  { 'balanceOfPaymentsId': 229, 'name': '229', 'description': '1.7.2 Freight' },
  { 'balanceOfPaymentsId': 230, 'name': '230', 'description': '1.7.3 Other' },
  { 'balanceOfPaymentsId': 231, 'name': '231', 'description': '1.8 Pipeline transport and electricity transmission' },
  { 'balanceOfPaymentsId': 232, 'name': '232', 'description': '1.9 Other supporting and auxiliary transport services' },
  { 'balanceOfPaymentsId': 236, 'name': '236', 'description': '2. Travel' },
  { 'balanceOfPaymentsId': 237, 'name': '237', 'description': '2.1 Business travel' },
  { 'balanceOfPaymentsId': 238, 'name': '238', 'description': '2.1.1 Expenditure by seasonal and border workers' },
  { 'balanceOfPaymentsId': 239, 'name': '239', 'description': '2.1.2 Other' },
  { 'balanceOfPaymentsId': 240, 'name': '240', 'description': '2.2 Personal travel' },
  { 'balanceOfPaymentsId': 241, 'name': '241', 'description': '2.2.1 Health-related expenditure' },
  { 'balanceOfPaymentsId': 242, 'name': '242', 'description': '2.2.2 Education-related expenditure' },
  { 'balanceOfPaymentsId': 243, 'name': '243', 'description': '2.2.3 Other' },
  { 'balanceOfPaymentsId': 245, 'name': '245', 'description': '3. Communications services' },
  { 'balanceOfPaymentsId': 246, 'name': '246', 'description': '3.1 Postal and courier services' },
  { 'balanceOfPaymentsId': 247, 'name': '247', 'description': '3.2 Telecommunications Services' },
  { 'balanceOfPaymentsId': 249, 'name': '249', 'description': '4. Construction services' },
  { 'balanceOfPaymentsId': 250, 'name': '250', 'description': '4.1 Construction abroad' },
  { 'balanceOfPaymentsId': 251, 'name': '251', 'description': '4.2 Construction in the compiling economy' },
  { 'balanceOfPaymentsId': 253, 'name': '253', 'description': '5. Insurance services' },
  { 'balanceOfPaymentsId': 254, 'name': '254', 'description': '5.1 Life insurance and pension funding' },
  { 'balanceOfPaymentsId': 255, 'name': '255', 'description': '5.2 Freight insurance' },
  { 'balanceOfPaymentsId': 256, 'name': '256', 'description': '5.3 Other direct insurance' },
  { 'balanceOfPaymentsId': 257, 'name': '257', 'description': '5.4 Reinsurance' },
  { 'balanceOfPaymentsId': 258, 'name': '258', 'description': '5.5 Auxiliary services' },
  { 'balanceOfPaymentsId': 260, 'name': '260', 'description': '6. Financial services' },
  { 'balanceOfPaymentsId': 262, 'name': '262', 'description': '7. Computer and information services' },
  { 'balanceOfPaymentsId': 263, 'name': '263', 'description': '7.1 Computer services' },
  { 'balanceOfPaymentsId': 264, 'name': '264', 'description': '7.2 Information services' },
  { 'balanceOfPaymentsId': 889, 'name': '889', 'description': '7.2.1 News agency services' },
  { 'balanceOfPaymentsId': 890, 'name': '890', 'description': '7.2.2 Other information provision services' },
  { 'balanceOfPaymentsId': 266, 'name': '266', 'description': '8. Royalties and license fees' },
  { 'balanceOfPaymentsId': 891, 'name': '891', 'description': '8.1 Franchises and similar rights' },
  { 'balanceOfPaymentsId': 892, 'name': '892', 'description': '8.2 Other royalties and license fees' },
  { 'balanceOfPaymentsId': 268, 'name': '268', 'description': '9. Other business services' },
  { 'balanceOfPaymentsId': 269, 'name': '269', 'description': '9.1 Merchanting and other trade-related services' },
  { 'balanceOfPaymentsId': 270, 'name': '270', 'description': '9.1.1 Merchanting' },
  { 'balanceOfPaymentsId': 271, 'name': '271', 'description': '9.1.2 Other trade-related services' },
  { 'balanceOfPaymentsId': 272, 'name': '272', 'description': '9.2 Operational leasing services' },
  { 'balanceOfPaymentsId': 273, 'name': '273', 'description': '9.3 Miscellaneous business, professional, and technical services' },
  { 'balanceOfPaymentsId': 274, 'name': '274', 'description': '9.3.1 Legal, accounting, management consulting, and public relations' },
  { 'balanceOfPaymentsId': 275, 'name': '275', 'description': '9.3.1.1 Legal services' },
  { 'balanceOfPaymentsId': 276, 'name': '276', 'description': '9.3.1.2 Accounting, auditing, bookkeeping, and tax consulting services' },
  { 'balanceOfPaymentsId': 277, 'name': '277', 'description': '9.3.1.3 Business and management consulting and public relations services' },
  { 'balanceOfPaymentsId': 278, 'name': '278', 'description': '9.3.2 Advertising, market research, and public opinion polling' },
  { 'balanceOfPaymentsId': 279, 'name': '279', 'description': '9.3.3 Research and development' },
  { 'balanceOfPaymentsId': 280, 'name': '280', 'description': '9.3.4 Architectural, engineering, and other technical services' },
  { 'balanceOfPaymentsId': 281, 'name': '281', 'description': '9.3.5 Agricultural, mining, and on-site processing services' },
  { 'balanceOfPaymentsId': 282, 'name': '282', 'description': '9.3.5.1 Waste treatment and depollution' },
  { 'balanceOfPaymentsId': 283, 'name': '283', 'description': '9.3.5.2 Agricultural, mining, and other on-site processing services' },
  { 'balanceOfPaymentsId': 284, 'name': '284', 'description': '9.3.6 Other business services' },
  { 'balanceOfPaymentsId': 285, 'name': '285', 'description': '9.3.7 Services between related enterprises, n.i.e.' },
  { 'balanceOfPaymentsId': 287, 'name': '287', 'description': '10. Personal, cultural, and recreational services' },
  { 'balanceOfPaymentsId': 288, 'name': '288', 'description': '10.1 Audiovisual and related services' },
  { 'balanceOfPaymentsId': 289, 'name': '289', 'description': '10.2 Other personal, cultural, and recreational services' },
  { 'balanceOfPaymentsId': 895, 'name': '895', 'description': '10.2.1 Education services' },
  { 'balanceOfPaymentsId': 896, 'name': '896', 'description': '10.2.2 Health services' },
  { 'balanceOfPaymentsId': 897, 'name': '897', 'description': '10.2.3 Other' },
  { 'balanceOfPaymentsId': 291, 'name': '291', 'description': '11. Government services, n.i.e.' },
  { 'balanceOfPaymentsId': 292, 'name': '292', 'description': '11.1 Embassies and consulates' },
  { 'balanceOfPaymentsId': 293, 'name': '293', 'description': '11.2 Military units and agencies' },
  { 'balanceOfPaymentsId': 294, 'name': '294', 'description': '11.3 Other government services' },
  { 'balanceOfPaymentsId': 300, 'name': '300', 'description': 'C. Income' },
  { 'balanceOfPaymentsId': 310, 'name': '310', 'description': '1. Compensation of employees including border, seasonal, and other workers' },
  { 'balanceOfPaymentsId': 320, 'name': '320', 'description': '2. Investment income' },
  { 'balanceOfPaymentsId': 330, 'name': '330', 'description': '2.1 Direct investment' },
  { 'balanceOfPaymentsId': 331, 'name': '331', 'description': '2.1.1 Income on equity' },
  { 'balanceOfPaymentsId': 332, 'name': '332', 'description': '2.1.1.1 Dividends and distributed branch profits' },
  { 'balanceOfPaymentsId': 333, 'name': '333', 'description': '2.1.1.2 Reinvested earnings and undistributed branch profits' },
  { 'balanceOfPaymentsId': 334, 'name': '334', 'description': '2.1.2 Income on debt (interest)' },
  { 'balanceOfPaymentsId': 339, 'name': '339', 'description': '2.2 Portfolio investment' },
  { 'balanceOfPaymentsId': 340, 'name': '340', 'description': '2.2.1 Income on equity (dividends)' },
  { 'balanceOfPaymentsId': 341, 'name': '341', 'description': '2.2.1.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 342, 'name': '342', 'description': '2.2.1.2 General government' },
  { 'balanceOfPaymentsId': 343, 'name': '343', 'description': '2.2.1.3 Banks' },
  { 'balanceOfPaymentsId': 344, 'name': '344', 'description': '2.2.1.4 Other sectors' },
  { 'balanceOfPaymentsId': 349, 'name': '349', 'description': '2.2.2 Income on debt (interest)' },
  { 'balanceOfPaymentsId': 350, 'name': '350', 'description': '2.2.2.1 Bonds and notes' },
  { 'balanceOfPaymentsId': 351, 'name': '351', 'description': '2.2.2.1.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 352, 'name': '352', 'description': '2.2.2.1.2 General government' },
  { 'balanceOfPaymentsId': 353, 'name': '353', 'description': '2.2.2.1.3 Banks' },
  { 'balanceOfPaymentsId': 354, 'name': '354', 'description': '2.2.2.1.4 Other sectors' },
  { 'balanceOfPaymentsId': 360, 'name': '360', 'description': '2.2.2.2 Money-market instruments' },
  { 'balanceOfPaymentsId': 361, 'name': '361', 'description': '2.2.2.2.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 362, 'name': '362', 'description': '2.2.2.2.2 General government' },
  { 'balanceOfPaymentsId': 363, 'name': '363', 'description': '2.2.2.2.3 Banks' },
  { 'balanceOfPaymentsId': 364, 'name': '364', 'description': '2.2.2.2.4 Other sectors' },
  { 'balanceOfPaymentsId': 370, 'name': '370', 'description': '2.3 Other investment' },
  { 'balanceOfPaymentsId': 371, 'name': '371', 'description': '2.3.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 372, 'name': '372', 'description': '2.3.2 General government' },
  { 'balanceOfPaymentsId': 373, 'name': '373', 'description': '2.3.3 Banks' },
  { 'balanceOfPaymentsId': 374, 'name': '374', 'description': '2.3.4 Other sectors' },
  { 'balanceOfPaymentsId': 379, 'name': '379', 'description': 'D. Current transfers' },
  { 'balanceOfPaymentsId': 380, 'name': '380', 'description': '1. General government' },
  { 'balanceOfPaymentsId': 38010, 'name': '380 EC', 'description': 'Exc. Fin. - Intergovernmental grants' },
  { 'balanceOfPaymentsId': 38020, 'name': '380 ED', 'description': 'Exc. Fin. - Grants received from Fund subsidy accounts' },
  { 'balanceOfPaymentsId': 38030, 'name': '380 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 390, 'name': '390', 'description': '2. Other sectors' },
  { 'balanceOfPaymentsId': 391, 'name': '391', 'description': '2.1 Workers\' remittances' },
  { 'balanceOfPaymentsId': 392, 'name': '392', 'description': '2.2 Other transfers' },
  { 'balanceOfPaymentsId': 996, 'name': '996', 'description': 'Capital and Financial Account' },
  { 'balanceOfPaymentsId': 994, 'name': '994', 'description': 'E. Capital Account' },
  { 'balanceOfPaymentsId': 400, 'name': '400', 'description': '1. Capital transfers' },
  { 'balanceOfPaymentsId': 401, 'name': '401', 'description': '1.1 General government' },
  { 'balanceOfPaymentsId': 402, 'name': '402', 'description': '1.1.1 Debt forgiveness' },
  { 'balanceOfPaymentsId': 40210, 'name': '402 EB', 'description': 'Exceptional Financing' },
  { 'balanceOfPaymentsId': 40220, 'name': '402 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 410, 'name': '410', 'description': '1.1.2 Other' },
  { 'balanceOfPaymentsId': 430, 'name': '430', 'description': '1.2 Other sectors' },
  { 'balanceOfPaymentsId': 431, 'name': '431', 'description': '1.2.1 Migrants\' transfers' },
  { 'balanceOfPaymentsId': 432, 'name': '432', 'description': '1.2.2 Debt forgiveness' },
  { 'balanceOfPaymentsId': 440, 'name': '440', 'description': '1.2.3 Other' },
  { 'balanceOfPaymentsId': 480, 'name': '480', 'description': '2. Acquisitions/disposal of non-produced nonfinancial assets' },
  { 'balanceOfPaymentsId': 995, 'name': '995', 'description': 'F. Financial Account' },
  { 'balanceOfPaymentsId': 500, 'name': '500', 'description': '1. Direct investment' },
  { 'balanceOfPaymentsId': 505, 'name': '505', 'description': '1.1 Abroad' },
  { 'balanceOfPaymentsId': 510, 'name': '510', 'description': '1.1.1 Equity capital' },
  { 'balanceOfPaymentsId': 515, 'name': '515', 'description': '1.1.1.1 Claims on affiliated enterprises' },
  { 'balanceOfPaymentsId': 520, 'name': '520', 'description': '1.1.1.2 Liabilities to affiliated enterprises' },
  { 'balanceOfPaymentsId': 525, 'name': '525', 'description': '1.1.2 Reinvested earnings' },
  { 'balanceOfPaymentsId': 526, 'name': '526', 'description': '1.1.2.1 Claims' },
  { 'balanceOfPaymentsId': 527, 'name': '527', 'description': '1.1.2.2 Liabilities' },
  { 'balanceOfPaymentsId': 530, 'name': '530', 'description': '1.1.3 Other capital' },
  { 'balanceOfPaymentsId': 535, 'name': '535', 'description': '1.1.3.1 Claims on affiliated enterprises' },
  { 'balanceOfPaymentsId': 540, 'name': '540', 'description': '1.1.3.2 Liabilities to affiliated enterprises' },
  { 'balanceOfPaymentsId': 555, 'name': '555', 'description': '1.2 In reporting economy' },
  { 'balanceOfPaymentsId': 560, 'name': '560', 'description': '1.2.1 Equity capital' },
  { 'balanceOfPaymentsId': 565, 'name': '565', 'description': '1.2.1.1 Claims on direct investors' },
  { 'balanceOfPaymentsId': 570, 'name': '570', 'description': '1.2.1.2 Liabilities to direct investors' },
  { 'balanceOfPaymentsId': 57010, 'name': '570 EF', 'description': 'Exc. Fin. - Investment associated with debt reduction' },
  { 'balanceOfPaymentsId': 57020, 'name': '570 EG', 'description': 'Exc. Fin. - Other' },
  { 'balanceOfPaymentsId': 57030, 'name': '570 Z', 'description': '1.2.1.3 Other' },
  { 'balanceOfPaymentsId': 575, 'name': '575', 'description': '1.2.2 Reinvested earnings' },
  { 'balanceOfPaymentsId': 576, 'name': '576', 'description': '1.2.2.1 Claims' },
  { 'balanceOfPaymentsId': 577, 'name': '577', 'description': '1.2.2.2 Liabilities' },
  { 'balanceOfPaymentsId': 580, 'name': '580', 'description': '1.2.3 Other capital' },
  { 'balanceOfPaymentsId': 585, 'name': '585', 'description': '1.2.3.1 Claims on direct investors' },
  { 'balanceOfPaymentsId': 590, 'name': '590', 'description': '1.2.3.2 Liabilities to direct investors' },
  { 'balanceOfPaymentsId': 600, 'name': '600', 'description': '2. Portfolio investment' },
  { 'balanceOfPaymentsId': 602, 'name': '602', 'description': '2.1 Assets' },
  { 'balanceOfPaymentsId': 610, 'name': '610', 'description': '2.1.1 Equity securities' },
  { 'balanceOfPaymentsId': 611, 'name': '611', 'description': '2.1.1.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 612, 'name': '612', 'description': '2.1.1.2 General government' },
  { 'balanceOfPaymentsId': 613, 'name': '613', 'description': '2.1.1.3 Banks' },
  { 'balanceOfPaymentsId': 614, 'name': '614', 'description': '2.1.1.4 Other sectors' },
  { 'balanceOfPaymentsId': 619, 'name': '619', 'description': '2.1.2 Debt securities' },
  { 'balanceOfPaymentsId': 620, 'name': '620', 'description': '2.1.2.1 Bonds and notes' },
  { 'balanceOfPaymentsId': 621, 'name': '621', 'description': '2.1.2.1.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 622, 'name': '622', 'description': '2.1.2.1.2 General government' },
  { 'balanceOfPaymentsId': 623, 'name': '623', 'description': '2.1.2.1.3 Banks' },
  { 'balanceOfPaymentsId': 624, 'name': '624', 'description': '2.1.2.1.4 Other sectors' },
  { 'balanceOfPaymentsId': 630, 'name': '630', 'description': '2.1.2.2 Money market instruments' },
  { 'balanceOfPaymentsId': 631, 'name': '631', 'description': '2.1.2.2.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 632, 'name': '632', 'description': '2.1.2.2.2 General government' },
  { 'balanceOfPaymentsId': 633, 'name': '633', 'description': '2.1.2.2.3 Banks' },
  { 'balanceOfPaymentsId': 634, 'name': '634', 'description': '2.1.2.2.4 Other sectors' },
  { 'balanceOfPaymentsId': 652, 'name': '652', 'description': '2.2 Liabilities' },
  { 'balanceOfPaymentsId': 660, 'name': '660', 'description': '2.2.1 Equity securities' },
  { 'balanceOfPaymentsId': 663, 'name': '663', 'description': '2.2.1.1 Banks' },
  { 'balanceOfPaymentsId': 664, 'name': '664', 'description': '2.2.1.2 Other sectors' },
  { 'balanceOfPaymentsId': 669, 'name': '669', 'description': '2.2.2 Debt securities' },
  { 'balanceOfPaymentsId': 670, 'name': '670', 'description': '2.2.2.1 Bonds and notes' },
  { 'balanceOfPaymentsId': 671, 'name': '671', 'description': '2.2.2.1.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 67110, 'name': '671 EH', 'description': 'Exc. Fin. - Issues' },
  { 'balanceOfPaymentsId': 67120, 'name': '671 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 67130, 'name': '671 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 672, 'name': '672', 'description': '2.2.2.1.2 General government' },
  { 'balanceOfPaymentsId': 67210, 'name': '672 EH', 'description': 'Exc. Fin. - Issues' },
  { 'balanceOfPaymentsId': 67220, 'name': '672 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 67230, 'name': '672 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 673, 'name': '673', 'description': '2.2.2.1.3 Banks' },
  { 'balanceOfPaymentsId': 67310, 'name': '673 EH', 'description': 'Exc. Fin. - Issues' },
  { 'balanceOfPaymentsId': 67320, 'name': '673 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 67330, 'name': '673 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 674, 'name': '674', 'description': '2.2.2.1.4 Other sectors' },
  { 'balanceOfPaymentsId': 67410, 'name': '674 EH', 'description': 'Exc. Fin. - Issues' },
  { 'balanceOfPaymentsId': 67420, 'name': '674 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 67430, 'name': '674 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 680, 'name': '680', 'description': '2.2.2.2 Money market instruments' },
  { 'balanceOfPaymentsId': 681, 'name': '681', 'description': '2.2.2.2.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 68110, 'name': '681 EH', 'description': 'Exc. Fin. - Issues' },
  { 'balanceOfPaymentsId': 68120, 'name': '681 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 682, 'name': '682', 'description': '2.2.2.2.2 General government' },
  { 'balanceOfPaymentsId': 68210, 'name': '682 EH', 'description': 'Exc. Fin. - Issues' },
  { 'balanceOfPaymentsId': 68220, 'name': '682 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 683, 'name': '683', 'description': '2.2.2.2.3 Banks' },
  { 'balanceOfPaymentsId': 68310, 'name': '683 EH', 'description': 'Exc. Fin. - Issues' },
  { 'balanceOfPaymentsId': 68320, 'name': '683 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 684, 'name': '684', 'description': '2.2.2.2.4 Other sectors' },
  { 'balanceOfPaymentsId': 68410, 'name': '684 EH', 'description': 'Exc. Fin. - Issues' },
  { 'balanceOfPaymentsId': 68420, 'name': '684 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 910, 'name': '910', 'description': '3. Financial derivatives (net)' },
  { 'balanceOfPaymentsId': 911, 'name': '911', 'description': '3.0.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 912, 'name': '912', 'description': '3.0.2 General government' },
  { 'balanceOfPaymentsId': 913, 'name': '913', 'description': '3.0.3 Banks' },
  { 'balanceOfPaymentsId': 914, 'name': '914', 'description': '3.0.4 Other sectors' },
  { 'balanceOfPaymentsId': 900, 'name': '900', 'description': '3.1 Financial derivatives assets' },
  { 'balanceOfPaymentsId': 901, 'name': '901', 'description': '3.1.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 902, 'name': '902', 'description': '3.1.2 General government' },
  { 'balanceOfPaymentsId': 903, 'name': '903', 'description': '3.1.3 Banks' },
  { 'balanceOfPaymentsId': 904, 'name': '904', 'description': '3.1.4 Other sectors' },
  { 'balanceOfPaymentsId': 905, 'name': '905', 'description': '3.2 Financial derivatives liabilities' },
  { 'balanceOfPaymentsId': 906, 'name': '906', 'description': '3.2.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 907, 'name': '907', 'description': '3.2.2 General government' },
  { 'balanceOfPaymentsId': 908, 'name': '908', 'description': '3.2.3 Banks' },
  { 'balanceOfPaymentsId': 909, 'name': '909', 'description': '3.2.4 Other sectors' },
  { 'balanceOfPaymentsId': 700, 'name': '700', 'description': '4. Other investment' },
  { 'balanceOfPaymentsId': 703, 'name': '703', 'description': '4.1 Assets' },
  { 'balanceOfPaymentsId': 706, 'name': '706', 'description': '4.1.1 Trade credits' },
  { 'balanceOfPaymentsId': 707, 'name': '707', 'description': '4.1.1.1 General government' },
  { 'balanceOfPaymentsId': 708, 'name': '708', 'description': '4.1.1.1.1 Long-term' },
  { 'balanceOfPaymentsId': 709, 'name': '709', 'description': '4.1.1.1.2 Short-term' },
  { 'balanceOfPaymentsId': 710, 'name': '710', 'description': '4.1.1.2 Other sectors' },
  { 'balanceOfPaymentsId': 711, 'name': '711', 'description': '4.1.1.2.1 Long-term' },
  { 'balanceOfPaymentsId': 712, 'name': '712', 'description': '4.1.1.2.2 Short-term' },
  { 'balanceOfPaymentsId': 714, 'name': '714', 'description': '4.1.2 Loans' },
  { 'balanceOfPaymentsId': 715, 'name': '715', 'description': '4.1.2.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 717, 'name': '717', 'description': '4.1.2.1.1 Long-term' },
  { 'balanceOfPaymentsId': 718, 'name': '718', 'description': '4.1.2.1.2 Short-term' },
  { 'balanceOfPaymentsId': 719, 'name': '719', 'description': '4.1.2.2 General government' },
  { 'balanceOfPaymentsId': 720, 'name': '720', 'description': '4.1.2.2.1 Long-term' },
  { 'balanceOfPaymentsId': 721, 'name': '721', 'description': '4.1.2.2.2 Short-term' },
  { 'balanceOfPaymentsId': 722, 'name': '722', 'description': '4.1.2.3 Banks' },
  { 'balanceOfPaymentsId': 723, 'name': '723', 'description': '4.1.2.3.1 Long-term' },
  { 'balanceOfPaymentsId': 724, 'name': '724', 'description': '4.1.2.3.2 Short-term' },
  { 'balanceOfPaymentsId': 725, 'name': '725', 'description': '4.1.2.4 Other sectors' },
  { 'balanceOfPaymentsId': 726, 'name': '726', 'description': '4.1.2.4.1 Long-term' },
  { 'balanceOfPaymentsId': 727, 'name': '727', 'description': '4.1.2.4.2 Short-term' },
  { 'balanceOfPaymentsId': 730, 'name': '730', 'description': '4.1.3 Currency and deposits' },
  { 'balanceOfPaymentsId': 731, 'name': '731', 'description': '4.1.3.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 732, 'name': '732', 'description': '4.1.3.2 General government' },
  { 'balanceOfPaymentsId': 733, 'name': '733', 'description': '4.1.3.3 Banks' },
  { 'balanceOfPaymentsId': 734, 'name': '734', 'description': '4.1.3.4 Other sectors' },
  { 'balanceOfPaymentsId': 736, 'name': '736', 'description': '4.1.4 Other assets' },
  { 'balanceOfPaymentsId': 737, 'name': '737', 'description': '4.1.4.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 738, 'name': '738', 'description': '4.1.4.1.1 Long-term' },
  { 'balanceOfPaymentsId': 739, 'name': '739', 'description': '4.1.4.1.2 Short-term' },
  { 'balanceOfPaymentsId': 740, 'name': '740', 'description': '4.1.4.2 General government' },
  { 'balanceOfPaymentsId': 741, 'name': '741', 'description': '4.1.4.2.1 Long-term' },
  { 'balanceOfPaymentsId': 742, 'name': '742', 'description': '4.1.4.2.2 Short-term' },
  { 'balanceOfPaymentsId': 743, 'name': '743', 'description': '4.1.4.3 Banks' },
  { 'balanceOfPaymentsId': 744, 'name': '744', 'description': '4.1.4.3.1 Long-term' },
  { 'balanceOfPaymentsId': 745, 'name': '745', 'description': '4.1.4.3.2 Short-term' },
  { 'balanceOfPaymentsId': 746, 'name': '746', 'description': '4.1.4.4 Other sectors' },
  { 'balanceOfPaymentsId': 747, 'name': '747', 'description': '4.1.4.4.1 Long-term' },
  { 'balanceOfPaymentsId': 748, 'name': '748', 'description': '3.1.4.4.2 Short-term' },
  { 'balanceOfPaymentsId': 753, 'name': '753', 'description': '4.2 Liabilities' },
  { 'balanceOfPaymentsId': 756, 'name': '756', 'description': '4.2.1 Trade credits' },
  { 'balanceOfPaymentsId': 757, 'name': '757', 'description': '4.2.1.1 General government' },
  { 'balanceOfPaymentsId': 758, 'name': '758', 'description': '4.2.1.1.1 Long-term' },
  { 'balanceOfPaymentsId': 759, 'name': '759', 'description': '4.2.1.1.2 Short-term' },
  { 'balanceOfPaymentsId': 760, 'name': '760', 'description': '4.2.1.2 Other sectors' },
  { 'balanceOfPaymentsId': 761, 'name': '761', 'description': '4.2.1.2.1 Long-term' },
  { 'balanceOfPaymentsId': 762, 'name': '762', 'description': '4.2.1.2.2 Short-term' },
  { 'balanceOfPaymentsId': 764, 'name': '764', 'description': '4.2.2 Loans' },
  { 'balanceOfPaymentsId': 765, 'name': '765', 'description': '4.2.2.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 766, 'name': '766', 'description': '4.2.2.1.1 Use of Fund credit and loans from the Fund' },
  { 'balanceOfPaymentsId': 767, 'name': '767', 'description': '4.2.2.1.2 Other long-term' },
  { 'balanceOfPaymentsId': 76710, 'name': '767 EJ', 'description': 'Exc. Fin. - Drawings on new loans by authorities or other sectors onauthorities\' behalf' },
  { 'balanceOfPaymentsId': 76720, 'name': '767 EK', 'description': 'Exc. Fin. - Rescheduling of existing debt' },
  { 'balanceOfPaymentsId': 76730, 'name': '767 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 76740, 'name': '767 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 768, 'name': '768', 'description': '4.2.2.1.3 Short-term' },
  { 'balanceOfPaymentsId': 76810, 'name': '768 EJ', 'description': 'Exc. Fin. - Drawings on new loans by authorities or other sectors on authorities\' behalf' },
  { 'balanceOfPaymentsId': 76820, 'name': '768 EK', 'description': 'Exc. Fin. - Rescheduling of existing debt' },
  { 'balanceOfPaymentsId': 76830, 'name': '768 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 76840, 'name': '768 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 769, 'name': '769', 'description': '4.2.2.2 General government' },
  { 'balanceOfPaymentsId': 770, 'name': '770', 'description': '4.2.2.2.1 Long-term' },
  { 'balanceOfPaymentsId': 77010, 'name': '770 EJ', 'description': 'Exc. Fin. - Drawings on new loans by authorities or other sectors on authorities\' behalf' },
  { 'balanceOfPaymentsId': 77020, 'name': '770 EK', 'description': 'Exc. Fin. - Rescheduling of existing debt' },
  { 'balanceOfPaymentsId': 77030, 'name': '770 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 77040, 'name': '770 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 771, 'name': '771', 'description': '4.2.2.2.2 Short-term' },
  { 'balanceOfPaymentsId': 77110, 'name': '771 EJ', 'description': 'Exc. Fin. - Drawings on new loans by authorities or other sectors on authorities\' behalf' },
  { 'balanceOfPaymentsId': 77120, 'name': '771 EK', 'description': 'Exc. Fin. - Rescheduling of existing debt' },
  { 'balanceOfPaymentsId': 77130, 'name': '771 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 77140, 'name': '771 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 772, 'name': '772', 'description': '4.2.2.3 Banks' },
  { 'balanceOfPaymentsId': 773, 'name': '773', 'description': '4.2.2.3.1 Long-term' },
  { 'balanceOfPaymentsId': 77310, 'name': '773 EJ', 'description': 'Exc. Fin. - Drawings on new loans by authorities or other sectors on authorities\' behalf' },
  { 'balanceOfPaymentsId': 77320, 'name': '773 EK', 'description': 'Exc. Fin. - Rescheduling of existing debt' },
  { 'balanceOfPaymentsId': 77330, 'name': '773 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 77340, 'name': '773 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 774, 'name': '774', 'description': '4.2.2.3.2 Short-term' },
  { 'balanceOfPaymentsId': 77410, 'name': '774 EJ', 'description': 'Exc. Fin. - Drawings on new loans by authorities or other sectors on authorities\' behalf' },
  { 'balanceOfPaymentsId': 77420, 'name': '774 EK', 'description': 'Exc. Fin. - Rescheduling of existing debt' },
  { 'balanceOfPaymentsId': 77430, 'name': '774 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 77440, 'name': '774 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 775, 'name': '775', 'description': '4.2.2.4 Other sectors' },
  { 'balanceOfPaymentsId': 776, 'name': '776', 'description': '4.2.2.4.1 Long-term' },
  { 'balanceOfPaymentsId': 77610, 'name': '776 EJ', 'description': 'Exc. Fin. - Drawings on new loans by authorities or other sectors on authorities\' behalf' },
  { 'balanceOfPaymentsId': 77620, 'name': '776 EK', 'description': 'Exc. Fin. - Rescheduling of existing debt' },
  { 'balanceOfPaymentsId': 77630, 'name': '776 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 77640, 'name': '776 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 777, 'name': '777', 'description': '4.2.2.4.2 Short-term' },
  { 'balanceOfPaymentsId': 77710, 'name': '777 EJ', 'description': 'Exc. Fin. - Drawings on new loans by authorities or other sectors on authorities\' behalf' },
  { 'balanceOfPaymentsId': 77720, 'name': '777 EK', 'description': 'Exc. Fin. - Rescheduling of existing debt' },
  { 'balanceOfPaymentsId': 77730, 'name': '777 EM', 'description': 'Exc. Fin. - Advance repayments' },
  { 'balanceOfPaymentsId': 77740, 'name': '777 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 780, 'name': '780', 'description': '4.2.3 Currency and deposits' },
  { 'balanceOfPaymentsId': 781, 'name': '781', 'description': '4.2.3.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 782, 'name': '782', 'description': '4.2.3.2 General government' },
  { 'balanceOfPaymentsId': 783, 'name': '783', 'description': '4.2.3.3 Banks' },
  { 'balanceOfPaymentsId': 784, 'name': '784', 'description': '4.2.3.4 Other sectors' },
  { 'balanceOfPaymentsId': 786, 'name': '786', 'description': '4.2.4 Other liabilities' },
  { 'balanceOfPaymentsId': 787, 'name': '787', 'description': '4.2.4.1 Monetary authorities' },
  { 'balanceOfPaymentsId': 788, 'name': '788', 'description': '4.2.4.1.1 Long-term' },
  { 'balanceOfPaymentsId': 789, 'name': '789', 'description': '4.2.4.1.2 Short-term' },
  { 'balanceOfPaymentsId': 78905, 'name': '789 F', 'description': 'Exc. Fin. - Total arrears' },
  { 'balanceOfPaymentsId': 78910, 'name': '789 FA', 'description': 'Exc. Fin. - Accumulation of arrears' },
  { 'balanceOfPaymentsId': 78915, 'name': '789 FB', 'description': 'Exc. Fin. - Principal on short-term debt' },
  { 'balanceOfPaymentsId': 78920, 'name': '789 FC', 'description': 'Exc. Fin. - Principal on long-term debt' },
  { 'balanceOfPaymentsId': 78925, 'name': '789 FD', 'description': 'Exc. Fin. - Original interest' },
  { 'balanceOfPaymentsId': 78930, 'name': '789 FE', 'description': 'Exc. Fin. - Penalty interest' },
  { 'balanceOfPaymentsId': 78935, 'name': '789 FF', 'description': 'Exc. Fin. - Repayments of arrears' },
  { 'balanceOfPaymentsId': 78940, 'name': '789 FG', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 78945, 'name': '789 FH', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 78950, 'name': '789 FI', 'description': 'Exc. Fin. - Rescheduling of arrears' },
  { 'balanceOfPaymentsId': 78955, 'name': '789 FJ', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 78960, 'name': '789 FK', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 78965, 'name': '789 FM', 'description': 'Exc. Fin. - Cancellation of arrears' },
  { 'balanceOfPaymentsId': 78970, 'name': '789 FN', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 78975, 'name': '789 FO', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 78980, 'name': '789 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 790, 'name': '790', 'description': '4.2.4.2 General government' },
  { 'balanceOfPaymentsId': 791, 'name': '791', 'description': '4.2.4.2.1 Long-term' },
  { 'balanceOfPaymentsId': 792, 'name': '792', 'description': '4.2.4.2.2 Short-term' },
  { 'balanceOfPaymentsId': 79205, 'name': '792 F', 'description': 'Exc. Fin. - Total arrears' },
  { 'balanceOfPaymentsId': 79210, 'name': '792 FA', 'description': 'Exc. Fin. - Accumulation of arrears' },
  { 'balanceOfPaymentsId': 79215, 'name': '792 FB', 'description': 'Exc. Fin. - Principal on short-term debt' },
  { 'balanceOfPaymentsId': 79220, 'name': '792 FC', 'description': 'Exc. Fin. - Principal on long-term debt' },
  { 'balanceOfPaymentsId': 79225, 'name': '792 FD', 'description': 'Exc. Fin. - Original interest' },
  { 'balanceOfPaymentsId': 79230, 'name': '792 FE', 'description': 'Exc. Fin. - Penalty interest' },
  { 'balanceOfPaymentsId': 79235, 'name': '792 FF', 'description': 'Exc. Fin. - Repayments of arrears' },
  { 'balanceOfPaymentsId': 79240, 'name': '792 FG', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79245, 'name': '792 FH', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79250, 'name': '792 FI', 'description': 'Exc. Fin. - Rescheduling of arrears' },
  { 'balanceOfPaymentsId': 79255, 'name': '792 FJ', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79260, 'name': '792 FK', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79265, 'name': '792 FM', 'description': 'Exc. Fin. - Cancellation of arrears' },
  { 'balanceOfPaymentsId': 79270, 'name': '792 FN', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79275, 'name': '792 FO', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79280, 'name': '792 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 793, 'name': '793', 'description': '4.2.4.3 Banks' },
  { 'balanceOfPaymentsId': 794, 'name': '794', 'description': '4.2.4.3.1 Long-term' },
  { 'balanceOfPaymentsId': 795, 'name': '795', 'description': '4.2.4.3.2 Short-term' },
  { 'balanceOfPaymentsId': 79505, 'name': '795 F', 'description': 'Exc. Fin. - Total arrears' },
  { 'balanceOfPaymentsId': 79510, 'name': '795 FA', 'description': 'Exc. Fin. - Accumulation of arrears' },
  { 'balanceOfPaymentsId': 79515, 'name': '795 FB', 'description': 'Exc. Fin. - Principal on short-term debt' },
  { 'balanceOfPaymentsId': 79520, 'name': '795 FC', 'description': 'Exc. Fin. - Principal on long-term debt' },
  { 'balanceOfPaymentsId': 79525, 'name': '795 FD', 'description': 'Exc. Fin. - Original interest' },
  { 'balanceOfPaymentsId': 79530, 'name': '795 FE', 'description': 'Exc. Fin. - Penalty interest' },
  { 'balanceOfPaymentsId': 79535, 'name': '795 FF', 'description': 'Exc. Fin. - Repayments of arrears' },
  { 'balanceOfPaymentsId': 79540, 'name': '795 FG', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79545, 'name': '795 FH', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79550, 'name': '795 FI', 'description': 'Exc. Fin. - Rescheduling of arrears' },
  { 'balanceOfPaymentsId': 79555, 'name': '795 FJ', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79560, 'name': '795 FK', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79565, 'name': '795 FM', 'description': 'Exc. Fin. - Cancellation of arrears' },
  { 'balanceOfPaymentsId': 79570, 'name': '795 FN', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79575, 'name': '795 FO', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79580, 'name': '795 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 796, 'name': '796', 'description': '4.2.4.4 Other sectors' },
  { 'balanceOfPaymentsId': 797, 'name': '797', 'description': '4.2.4.4.1 Long-term' },
  { 'balanceOfPaymentsId': 798, 'name': '798', 'description': '4.2.4.4.2 Short-term' },
  { 'balanceOfPaymentsId': 79805, 'name': '798 F', 'description': 'Exc. Fin. - Total arrears' },
  { 'balanceOfPaymentsId': 79810, 'name': '798 FA', 'description': 'Exc. Fin. - Accumulation of arrears' },
  { 'balanceOfPaymentsId': 79815, 'name': '798 FB', 'description': 'Exc. Fin. - Principal on short-term debt' },
  { 'balanceOfPaymentsId': 79820, 'name': '798 FC', 'description': 'Exc. Fin. - Principal on long-term debt' },
  { 'balanceOfPaymentsId': 79825, 'name': '798 FD', 'description': 'Exc. Fin. - Original interest' },
  { 'balanceOfPaymentsId': 79830, 'name': '798 FE', 'description': 'Exc. Fin. - Penalty interest' },
  { 'balanceOfPaymentsId': 79835, 'name': '798 FF', 'description': 'Exc. Fin. - Repayments of arrears' },
  { 'balanceOfPaymentsId': 79840, 'name': '798 FG', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79845, 'name': '798 FH', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79850, 'name': '798 FI', 'description': 'Exc. Fin. - Rescheduling of arrears' },
  { 'balanceOfPaymentsId': 79855, 'name': '798 FJ', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79860, 'name': '798 FK', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79865, 'name': '798 FM', 'description': 'Exc. Fin. - Cancellation of arrears' },
  { 'balanceOfPaymentsId': 79870, 'name': '798 FN', 'description': 'Exc. Fin. - Principal' },
  { 'balanceOfPaymentsId': 79875, 'name': '798 FO', 'description': 'Exc. Fin. - Interest' },
  { 'balanceOfPaymentsId': 79880, 'name': '798 Z', 'description': 'Other' },
  { 'balanceOfPaymentsId': 802, 'name': '802', 'description': '5. Official reserve assets' },
  { 'balanceOfPaymentsId': 812, 'name': '812', 'description': '5.1 Monetary gold (including gold deposits and, if appropriate, gold swapped)' },
  { 'balanceOfPaymentsId': 811, 'name': '811', 'description': '5.2 SDRs' },
  { 'balanceOfPaymentsId': 810, 'name': '810', 'description': '5.3 Reserve position in the Fund' },
  { 'balanceOfPaymentsId': 803, 'name': '803', 'description': '5.4 Foreign exchange' },
  { 'balanceOfPaymentsId': 808, 'name': '808', 'description': '5.4.1 Currency and deposits' },
  { 'balanceOfPaymentsId': 80810, 'name': '808 A', 'description': '5.4.1.1 With monetary authorities' },
  { 'balanceOfPaymentsId': 80820, 'name': '808 B', 'description': '5.4.1.2 With banks' },
  { 'balanceOfPaymentsId': 806, 'name': '806', 'description': '5.4.2 Securities' },
  { 'balanceOfPaymentsId': 80610, 'name': '806 S', 'description': '5.4.2.1 Equities' },
  { 'balanceOfPaymentsId': 80620, 'name': '806 T', 'description': '5.4.2.2 Bonds and notes' },
  { 'balanceOfPaymentsId': 80630, 'name': '806 U', 'description': '5.4.2.3 Money market instruments' },
  { 'balanceOfPaymentsId': 81440, 'name': '814 A', 'description': '5.5 Financial derivatives, net' },
  { 'balanceOfPaymentsId': 813, 'name': '813', 'description': '5.6 Other claims' },
  { 'balanceOfPaymentsId': 950, 'name': '950', 'description': '1. Freight transportation on merchandise, valued on a transaction basis' },
  { 'balanceOfPaymentsId': 951, 'name': '951', 'description': '1.1 Sea freight' },
  { 'balanceOfPaymentsId': 952, 'name': '952', 'description': '1.2 Air freight' },
  { 'balanceOfPaymentsId': 858, 'name': '858', 'description': '1.3 Other freight' },
  { 'balanceOfPaymentsId': 862, 'name': '862', 'description': '1.4 Space freight' },
  { 'balanceOfPaymentsId': 863, 'name': '863', 'description': '1.5 Rail freight' },
  { 'balanceOfPaymentsId': 953, 'name': '953', 'description': '1.6 Road freight' },
  { 'balanceOfPaymentsId': 865, 'name': '865', 'description': '1.7 Inland waterway freight' },
  { 'balanceOfPaymentsId': 868, 'name': '868', 'description': '1.8 Pipeline freight' },
  { 'balanceOfPaymentsId': 956, 'name': '956', 'description': '2.1 Expenditure on goods' },
  { 'balanceOfPaymentsId': 957, 'name': '957', 'description': '2.2 Expenditure on accommodation and food and beverage serving services' },
  { 'balanceOfPaymentsId': 871, 'name': '871', 'description': '2.3 All other travel expenditure' },
  { 'balanceOfPaymentsId': 960, 'name': '960', 'description': '3. Gross insurance premiums' },
  { 'balanceOfPaymentsId': 972, 'name': '972', 'description': '3.1 Gross premiums-life insurance' },
  { 'balanceOfPaymentsId': 974, 'name': '974', 'description': '3.2 Gross premiums-freight insurance' },
  { 'balanceOfPaymentsId': 976, 'name': '976', 'description': '3.3 Gross premiums-other direct insurance' },
  { 'balanceOfPaymentsId': 961, 'name': '961', 'description': '4. Gross insurance claims' },
  { 'balanceOfPaymentsId': 973, 'name': '973', 'description': '4.1 Gross claims-life insurance' },
  { 'balanceOfPaymentsId': 975, 'name': '975', 'description': '4.2 Gross claims-freight insurance' },
  { 'balanceOfPaymentsId': 977, 'name': '977', 'description': '4.3 Gross claims-other direct insurance' },
  { 'balanceOfPaymentsId': 887, 'name': '887', 'description': '5. Financial intermediation services indirectly measured (FISIM)' },
  { 'balanceOfPaymentsId': 888, 'name': '888', 'description': '6. Financial services including FISIM' },
  { 'balanceOfPaymentsId': 962, 'name': '962', 'description': '7. Merchanting gross flows' },
  { 'balanceOfPaymentsId': 894, 'name': '894', 'description': '8. Audiovisual transactions' },
  { 'balanceOfPaymentsId': 991, 'name': '991', 'description': 'Goods and services' },
  { 'balanceOfPaymentsId': 992, 'name': '992', 'description': 'Goods, services, and income' },
  { 'balanceOfPaymentsId': 982, 'name': '982', 'description': 'Current and capital transfers' },
  { 'balanceOfPaymentsId': 983, 'name': '983', 'description': 'Current + capital + financial accounts' },
  { 'balanceOfPaymentsId': 984, 'name': '984', 'description': 'Current + capital + financial accounts + net errors and omissions' },
  { 'balanceOfPaymentsId': 920, 'name': '920', 'description': 'Exceptional financing transactions (Total)' },
  { 'balanceOfPaymentsId': 998, 'name': '998', 'description': 'Net errors and omissions' }
]

exports.seed = async function (knex) {
  try {
    return await knex('balanceOfPayments').insert(balanceOfPayments)
  } catch (err) {
    if (err.code === 'ER_DUP_ENTRY') return -1001
    else {
      console.log(`Uploading seeds for balanceOfPayments has failed with the following error: ${err}`)
      return -1000
    }
  }
}
